### ISSUE TITLE
zlib-1.2.8 is now a fossil

### ISSUE THREAD

**Issue by lmignon** [acsone/acsone-manylinux-wheel-builder#1]
The zlib archive is now available from http://zlib.net/fossils/zlib-1.2.8.tar.gz
ping @sbidoul

**Comment by sbidoul** [comment]
This was resolved in https://github.com/acsone/acsone-manylinux-wheel-builder/commit/280e51d1370ef6977c9e82d0433cee9d9dcdeda5
