### ISSUE TITLE
Submit any of these upstream?

### ISSUE THREAD

**Issue by tkelman** [acsone/acsone-manylinux-wheel-builder#2]
I wanted to thank you for the wheels you have publicly built here. Have you considered contacting any of the upstream maintainers to see if they'd be interested in incorporating these in their release mechanisms? python-ldap is one example where there are no wheels on pypi and I was able to make good use of yours, but it would simplify future updates and be a little cleaner if the maintainers started building them.

**Comment by tkelman** [comment]
ping @sbidoul any opinion about this?

**Comment by sbidoul** [comment]
Hi, it would certainly be nice if upstream would provide the wheels. At the time, I considered it would would be faster to build this than chasing all upstream maintainers. I'd suggest you open an issue for each package where it's missing, and possibly link it here.

**Comment by sbidoul** [comment]
The good news is that the list of what we need to build ourselves is shrinking over time.

**Comment by tkelman** [comment]
I'm no longer involved in the project that was using python-ldap, but doesn't look like upstream is building wheels for that yet?
